services:
  redis:
    image: redis:8.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:16
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  solr:
    image: solr:9.0
    container_name: solr
    ports:
      - "8983:8983"
    volumes:
      - solr-data:/var/solr
    command:
      - solr-precreate
      - gettingstarted
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/"]
      interval: 10s
      timeout: 5s
      retries: 5

  meilisearch:
    image: getmeili/meilisearch:v1.16
    container_name: meilisearch
    ports:
      - "7700:7700"
    volumes:
      - meili-data:/meili_data
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_ENV=development
      - MEILI_NO_ANALYTICS=true
    command:
      - meilisearch
      - --db-path=/meili_data/data.ms
      - --master-key=${MEILI_MASTER_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  typesense:
    image: typesense/typesense:29.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data
    command: "--data-dir /data --api-key=xyz --enable-cors"

  surrealdb:
    image: surrealdb/surrealdb:latest
    command:
      - start
      - --user
      - root
      - --pass
      - root
    ports:
      - "8000:8000"
    volumes:
      - surrealdb-data:/data
    environment:
      - SURREALDB_ENV_USER=root
      - SURREALDB_ENV_PASS=root
    restart: unless-stopped

volumes:
  redis-data:
  pg-data:
  solr-data:
  meili-data:
  typesense-data:
  surrealdb-data:
